name: build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - run: rustup update --no-self-update
    - uses: Swatinem/rust-cache@v2.0.1
    - run: eng/build.sh
      shell: bash
    - name: upload artifacts
      uses: actions/upload-artifact@v3.1.1
      with:
        name: linux-artifacts
        path: |
          target/release/freta
          target/release/examples/analyze-az-vm
          target/release/examples/analyze-hyperv-vm
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - run: rustup update --no-self-update
    - uses: Swatinem/rust-cache@v2.0.1
    - run: eng/build.sh
      shell: bash
    - name: upload artifacts
      uses: actions/upload-artifact@v3.1.1
      with:
        name: windows-artifacts
        path: |
          target/release/freta.exe
          target/release/freta.pdb
          target/release/examples/analyze-az-vm.exe
          target/release/examples/analyze_az_vm.pdb
          target/release/examples/analyze-hyperv-vm.exe
          target/release/examples/analyze_hyperv_vm.pdb
